### PR TITLE
[UPDATED] Guests

### PR DESCRIPTION
**Pull request by atulyadav745**
@omprakash1999mina It should work now.
Please give your comments.

### CODE REVIEW

**Review by omprakash1999mina — CHANGES_REQUESTED** [review]
Same change the base branch to develop

**Comment by atulyadav745** [comment]
> Same change the base branch to develop

@omprakash1999mina I have to change this red circled branch from master to develop only??
WhatsApp Image 2022-10-10 at 14 37 20

**Comment by omprakash1999mina** [comment]
> > Same change the base branch to develop
> 
> @omprakash1999mina I have to change this red circled branch from master to develop only?? WhatsApp Image 2022-10-10 at 14 37 20

Yes

**Comment by atulyadav745** [comment]
> > > Same change the base branch to develop
> > 
> > 
> > @omprakash1999mina I have to change this red circled branch from master to develop only?? WhatsApp Image 2022-10-10 at 14 37 20
> 
> Yes

@omprakash1999mina Done. Please see if it is ready to merge.
WhatsApp Image 2022-10-10 at 15 08 56

**Comment by atulyadav745** [comment]
@omprakash1999mina  Bhaiya your comments?

**Comment by atulyadav745** [comment]
@omprakash1999mina  Bhaiya your comments?
Is it fine now?

**Pull request closed without merging**
