### PR TITLE
[UPDATED] Added brightness to darker images in guests 

### PR DESCRIPTION
**Pull request by atulyadav745**

### CODE REVIEW

**Comment by atulyadav745** [comment]
@omprakash1999mina Kindly review my PR and merge it. I have given brightness to some darker images.
Thank you
photo

**Review by omprakash1999mina — APPROVED** [review]
Nice work . 

this is a suggestion for you that  create the issue first.

**Review by omprakash1999mina — CHANGES_REQUESTED** [review]
please change the base branch from master to develop.

A developer should never open a PR to master all PR's go through the testing and staging .

**Review by omprakash1999mina — CHANGES_REQUESTED** [review]
And one thing change the title and make it in this way --> [UPDATED/ADDED/DELETED] then your work.

For reference see the commit history of master/develop branches.

**Comment by atulyadav745** [comment]
@omprakash1999mina Thanks for the feedback. I am very grateful to you.
I think that I have made the required changes.

**Review by omprakash1999mina — CHANGES_REQUESTED** [review]
Only guest section should be updated .
why these unnecessary file changes made ?

**Comment by omprakash1999mina** [comment]
> Only guest section should be updated . why these unnecessary file changes made ?

**Pull request closed without merging**
